version: "3"

services:
  web:
    build: '.'
    env_file:
      - '.env'
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - '.:/code'
    depends_on:
      - redis

  redis:
    container_name: 'redis'
    image: 'redis'
    ports:
      - '127.0.0.1:6379:6379'
